default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: auxiliary_rails_sandbox_development

test:
  <<: *default
  database: auxiliary_rails_sandbox_test

production:
  <<: *default
  database: auxiliary_rails_sandbox_production
  username: auxiliary_rails_sandbox
  password: <%= ENV['AUXILIARY_RAILS_SANDBOX_DATABASE_PASSWORD'] %>
